.gitignore, lib/sales_engine.rb, test/sales_engine_test.rb
Prelim test and sales engine setup complete
returning to white-boarding to figure out what goes where.
=> Sales engine 0

.gitignore, data/item_test.csv, lib/item.rb, lib/item_repository.rb, lib/merchant.rb, test/item_repository_test.rb, test/item_test.rb, test/merchant_test.rb, test/sales_engine_test.rb, test/test_helper.rb
Worked through refactoring item and itemrepo class.
added time to classes to get them functioning in rspec.
refactored minitests to pass with new updated information
general updates to codes to pass spec harness testing.
Driver navigatored as group.
passing all tests including all spec harness tests.
=> Item repo refactor

lib/sales_analyst.rb, lib/sales_engine.rb, test/sales_analyst_test.rb, test/test_helper.rb
Basic sales analyst creation tests and class structure. 
Driver-Navigator'd this with whole group.
=> Adds sales analysts test and basic class structure

Rakefile
Adds to Rakefile to run all tests in test folder together. Working as expected.
=> Add run all tests to Rakefile

lib/sales_analyst.rb, test/sales_analyst_test.rb
adds average items per merchant to sales analyst. All tests passing.
=> adds asserts instance of merchants in sales analyst

lib/sales_analyst.rb, lib/sales_engine.rb, test/sales_analyst_test.rb
slight git fire. All tests passing - same supposed updates as original sales analyst branch.
=> adds average items per merchant to sales analyst

lib/item.rb, lib/sales_analyst.rb, lib/sales_engine.rb, test/sales_analyst_test.rb
Removed redundant attr_readers to clean up redundancy.
Removed def
=> Meeting with sal

lib/playgroung.rb, lib/sales_analyst.rb, test/sales_analyst_test.rb
adds standard deviation and req. methods (driver-navigators with Anna and Vince) all of our tests pass
=> Standard deviation

lib/sales_analyst.rb, test/sales_analyst_test.rb
Iteration 1 business intelligence methods for SalesAnalyst and associated tests. 
Driver-navigator-d this with whole group.
Passing all tests and spec harness.
=> Sales analyst methods

lib/item_repository.rb, lib/merchant_repository.rb, lib/sales_engine.rb, test/merchant_repository_test.rb, test/sales_engine_test.rb
Refactors SalesEngine and MerchantRepo (and associated tests) so that SalesEngine now creates the merchant objects and passes an array of Merchants to the MerchantRepo. 
Passes all tests and spec harness.
=> Merchant repo refactor

lib/invoice.rb, lib/invoice_repository.rb, lib/item_repository.rb, lib/sales_engine.rb, test/invoice_repository_test.rb, test/invoice_test.rb, test/item_repository_test.rb, test/sales_analyst_test.rb, test/sales_engine_test.rb, test/test_helper.rb
Creates invoice repo and invoice class, fixes merge conflicts as well as simplecov rework. Increased loc coverage back to 100%.
=> Invoice repo

lib/sales_analyst.rb, lib/sales_engine.rb, test/sales_analyst_test.rb, test/sales_engine_test.rb
Refactor SalesEngine to send SalesAnalyst the repositories directly (rather than sending itself). Refactor SalesAnalyst tests to work with items/merchants directly rather than having to take CSV data. 
All tests pass, RSpec passes through Iteration 2 invoices (as expected). 
Driver-navigator'd this as a team.
=> Salesanalyst test refactor

lib/customer.rb, lib/customer_repository.rb, lib/sales_engine.rb, test/customer_repository_test.rb, test/customer_test.rb, test/sales_engine_test.rb, test/test_helper.rb
This creates the customer repo and customer classes.
the classes have been tied into sales engine. I have however run into issues in tying these classes into the sales_analyst.
However the sales_analyst is currently unaffected because of Anna's missing file_path = nil check so the tests in analyst still pass.
The classes meet all spec requirements and pass the spec harness alongside all their respective minitests.
=> Customer repo and customer classes

lib/invoice_item.rb, lib/sales_analyst.rb, lib/sales_engine.rb, test/invoice_item_repository_test.rb, test/sales_analyst_test.rb, test/sales_engine_test.rb
Adjusts testing and general function for sales analyst to allow for better testing and readability as we move forward.
=> Csv analyst and engine refactor

lib/sales_analyst.rb, test/sales_analyst_test.rb
This completes iteration 3.
creates associated tests and methods for the business intelligence and are fully working in minitest and rspec
driver navigatored with Anna and Nico through this to completion.
=> Iteration 3 business intel

lib/sales_analyst.rb, test/sales_analyst_test.rb
Adds all tests for iteration 4 methods. Implements total revenue by date method. Passes minitest and Rspec for that method.
Driver-navigator'd this as a team.
=> Merchant analytics

lib/sales_analyst.rb, test/sales_analyst_test.rb
adds find merchants with only one item method - passes minitest & rspec 
closes #56
=> adds merchants with only one item method

lib/sales_analyst.rb, test/sales_analyst_test.rb
=> adds revenue by merchant - passing test and rspec

lib/merchant_repository.rb, lib/sales_analyst.rb, test/sales_analyst_test.rb
Created a method that checks for pending invoices and will return merchants that meet those requirements.
Passes both our minitest and the spec harness.
closes #55
=> Adds merchants with pending invoice method, passes rspec and minitest

lib/sales_analyst.rb, test/sales_analyst_test.rb
Adds top revenue earners method. Passes spec harness and rake.
=> Top merchants#54

lib/math.rb, lib/sales_analyst.rb
Create a math module for the math methods in SalesAnalyst. Passing minitest and spec harness.
=> Adds math module for salesanalyst

lib/sales_analyst.rb, test/sales_analyst_test.rb
Passes Rspec and our own tests 
left in the previous method since that was our common sense approach.
=> Most sold item for merchant method #59

lib/sales_analyst.rb, test/sales_analyst_test.rb
closes #57
driver / navigatored with Anna and Vincent.
=> One item per month #57

lib/sales_analyst.rb
closes #38 
Refactors Golden Items
=> adds helper methods for golden items

test/sales_engine_test.rb
Refactor Sales Engine tests to include all CSV files. Tests all passing.
=> Refactors sales engine tests

lib/invoice_repository.rb, lib/sales_analyst.rb, test/invoice_repository_test.rb, test/sales_analyst_test.rb
Uses helper methods to shorten and clarify methods in SalesAnalyst. Adds tests as necessary. 
All tests passing, including spec harness.
=> Sales analyst refactor
